/**
 * vite.lib.config.ts
 *
 * Vite library-mode config for building the @pihanga2/shadcn npm package.
 *
 * This config is NOT used by the playground dev server (vite.config.ts handles
 * that).  It is invoked exclusively by scripts/build-core.mjs:
 *
 *   node scripts/build-core.mjs          # full build
 *   npx vite build --config vite.lib.config.ts   # Vite step only
 *
 * Output: dist-lib/
 *   dist-lib/cards/<card>/index.js       per-card ESM entry
 *   dist-lib/cards/core-index.js         root barrel (all core cards)
 *   dist-lib/cards/<card>/index.d.ts     TypeScript declarations
 *   dist-lib/package.json                publishable manifest (written by build-core.mjs)
 *   dist-lib/README.md                   (written by build-core.mjs)
 */

import path from "path";
import {readFileSync} from "fs";
import {fileURLToPath} from "url";
import react from "@vitejs/plugin-react";
import dts from "vite-plugin-dts";
import {defineConfig} from "vite";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Core card allowlist
// ---------------------------------------------------------------------------

const {cards: CORE_CARDS} = JSON.parse(
  readFileSync(path.join(__dirname, "scripts/core-cards.json"), "utf-8"),
) as {cards: string[]};

// ---------------------------------------------------------------------------
// Entry points — one per card + the root barrel
// ---------------------------------------------------------------------------

/**
 * Root barrel is generated by build-core.mjs before this config runs.
 * Per-card entries enable sub-path imports:
 *   import "@pihanga2/shadcn/cards/button"
 */
const entry: Record<string, string> = {
  "cards/core-index": path.resolve(__dirname, "src/cards/core-index.ts"),
  "cards/types": path.resolve(__dirname, "src/cards/types.ts"),
  "cards/icons": path.resolve(__dirname, "src/cards/icons.ts"),
};

for (const card of CORE_CARDS) {
  entry[`cards/${card}/index`] = path.resolve(
    __dirname,
    `src/cards/${card}/index.ts`,
  );
}

// ---------------------------------------------------------------------------
// External dependencies — never bundled into the output
// ---------------------------------------------------------------------------

/**
 * Peer deps + heavy optional deps are all external.
 * Light runtime deps (clsx, class-variance-authority, lucide-react, …) are
 * also external here — they are declared as `dependencies` in the generated
 * dist-lib/package.json so npm installs them automatically for consumers.
 */
const external = [
  // ── Peer deps ────────────────────────────────────────────────────────────
  "react",
  "react/jsx-runtime",
  "react-dom",
  "@pihanga2/core",
  "@pihanga2/cards",
  // ── Radix UI (all packages) ───────────────────────────────────────────────
  /^@radix-ui\//,
  /^radix-ui/,
  // ── Light runtime deps ────────────────────────────────────────────────────
  "lucide-react",
  "class-variance-authority",
  "clsx",
  "tailwind-merge",
  "sonner",
  // ── Excluded-card deps (guard; should never appear in core source) ─────────
  "lodash",
  /^@antv\//,
  "react-resizable-panels",
  "react-json-view-lite",
  /^react-markdown/,
  /^remark/,
  /^rehype/,
  /^unified/,
  "mermaid",
  /^highlight\.js/,
];

// ---------------------------------------------------------------------------
// Vite config
// ---------------------------------------------------------------------------

export default defineConfig({
  plugins: [
    react(),
    dts({
      include: [
        "src/cards",
        "src/lib",
        "src/components/theme-provider",
        "src/components/hooks",
      ],
      exclude: [
        "src/**/*.example.ts",
        "src/**/*.test.tsx",
        "src/playground/**",
        "src/app.*",
        "src/main.ts",
        "src/vite-env.d.ts",
      ],
      outDir: "dist-lib",
      // Keep one .d.ts per source file (matches preserveModules layout)
      rollupTypes: false,
      tsconfigPath: "./tsconfig.json",
    }),
  ],

  resolve: {
    alias: [
      {find: "@/lib", replacement: path.resolve(__dirname, "./src/lib")},
      {
        find: "@/registry",
        replacement: path.resolve(__dirname, "./src/components"),
      },
      {find: "@", replacement: path.resolve(__dirname, "./src")},
    ],
  },

  // Do NOT copy public/ into dist-lib/ — the /r/*.json shadcn registry files
  // and other static assets are only needed for the playground dev server /
  // GitHub Pages, not for the npm package.
  publicDir: false,

  build: {
    lib: {
      entry,
      formats: ["es"],
    },
    rollupOptions: {
      external,
      output: {
        // Preserve the src/ directory tree so import paths are predictable
        preserveModules: true,
        preserveModulesRoot: "src",
        entryFileNames: "[name].js",
        chunkFileNames: "[name].js",
        assetFileNames: "[name][extname]",
      },
    },
    outDir: "dist-lib",
    sourcemap: true,
    // Clear dist-lib/ before each build
    emptyOutDir: true,
  },
});
